package com.cuduchoa.ThiTracNghiem.mapper;

import com.cuduchoa.ThiTracNghiem.model.Subject;
import com.cuduchoa.ThiTracNghiem.model.SubjectExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    long countByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int deleteByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int deleteByPrimaryKey(Long subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int insert(Subject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int insertSelective(Subject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    List<Subject> selectByExample(SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    Subject selectByPrimaryKey(Long subjectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Subject row, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int updateByExample(@Param("row") Subject row, @Param("example") SubjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int updateByPrimaryKeySelective(Subject row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subjects
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    int updateByPrimaryKey(Subject row);
}