package com.cuduchoa.ThiTracNghiem.model;

public class Class_detailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_detail.class_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column class_detail.nguoidung_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_detail.class_id
     *
     * @return the value of class_detail.class_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_detail.class_id
     *
     * @param classId the value for class_detail.class_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column class_detail.nguoidung_id
     *
     * @return the value of class_detail.nguoidung_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungId() {
        return nguoidungId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column class_detail.nguoidung_id
     *
     * @param nguoidungId the value for class_detail.nguoidung_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungId(String nguoidungId) {
        this.nguoidungId = nguoidungId;
    }
}