package com.cuduchoa.ThiTracNghiem.model;

public class Class {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_year
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String classYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.class_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Boolean classState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_id
     *
     * @return the value of classes.class_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_id
     *
     * @param classId the value for classes.class_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setClassId(Long classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_name
     *
     * @return the value of classes.class_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_name
     *
     * @param className the value for classes.class_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_year
     *
     * @return the value of classes.class_year
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getClassYear() {
        return classYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_year
     *
     * @param classYear the value for classes.class_year
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setClassYear(String classYear) {
        this.classYear = classYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.class_state
     *
     * @return the value of classes.class_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Boolean getClassState() {
        return classState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.class_state
     *
     * @param classState the value for classes.class_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setClassState(Boolean classState) {
        this.classState = classState;
    }
}