package com.cuduchoa.ThiTracNghiem.model;

import java.util.Date;

public class Nguoidung {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_password
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_full_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungFullName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_email
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_phone_number
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungPhoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_role
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_date_of_birth
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Date nguoidungDateOfBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_address
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_gender
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_image
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String nguoidungImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nguoidung.nguoidung_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Boolean nguoidungState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_id
     *
     * @return the value of nguoidung.nguoidung_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungId() {
        return nguoidungId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_id
     *
     * @param nguoidungId the value for nguoidung.nguoidung_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungId(String nguoidungId) {
        this.nguoidungId = nguoidungId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_password
     *
     * @return the value of nguoidung.nguoidung_password
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungPassword() {
        return nguoidungPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_password
     *
     * @param nguoidungPassword the value for nguoidung.nguoidung_password
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungPassword(String nguoidungPassword) {
        this.nguoidungPassword = nguoidungPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_full_name
     *
     * @return the value of nguoidung.nguoidung_full_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungFullName() {
        return nguoidungFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_full_name
     *
     * @param nguoidungFullName the value for nguoidung.nguoidung_full_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungFullName(String nguoidungFullName) {
        this.nguoidungFullName = nguoidungFullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_email
     *
     * @return the value of nguoidung.nguoidung_email
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungEmail() {
        return nguoidungEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_email
     *
     * @param nguoidungEmail the value for nguoidung.nguoidung_email
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungEmail(String nguoidungEmail) {
        this.nguoidungEmail = nguoidungEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_phone_number
     *
     * @return the value of nguoidung.nguoidung_phone_number
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungPhoneNumber() {
        return nguoidungPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_phone_number
     *
     * @param nguoidungPhoneNumber the value for nguoidung.nguoidung_phone_number
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungPhoneNumber(String nguoidungPhoneNumber) {
        this.nguoidungPhoneNumber = nguoidungPhoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_role
     *
     * @return the value of nguoidung.nguoidung_role
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungRole() {
        return nguoidungRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_role
     *
     * @param nguoidungRole the value for nguoidung.nguoidung_role
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungRole(String nguoidungRole) {
        this.nguoidungRole = nguoidungRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_date_of_birth
     *
     * @return the value of nguoidung.nguoidung_date_of_birth
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Date getNguoidungDateOfBirth() {
        return nguoidungDateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_date_of_birth
     *
     * @param nguoidungDateOfBirth the value for nguoidung.nguoidung_date_of_birth
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungDateOfBirth(Date nguoidungDateOfBirth) {
        this.nguoidungDateOfBirth = nguoidungDateOfBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_address
     *
     * @return the value of nguoidung.nguoidung_address
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungAddress() {
        return nguoidungAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_address
     *
     * @param nguoidungAddress the value for nguoidung.nguoidung_address
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungAddress(String nguoidungAddress) {
        this.nguoidungAddress = nguoidungAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_gender
     *
     * @return the value of nguoidung.nguoidung_gender
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungGender() {
        return nguoidungGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_gender
     *
     * @param nguoidungGender the value for nguoidung.nguoidung_gender
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungGender(String nguoidungGender) {
        this.nguoidungGender = nguoidungGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_image
     *
     * @return the value of nguoidung.nguoidung_image
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getNguoidungImage() {
        return nguoidungImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_image
     *
     * @param nguoidungImage the value for nguoidung.nguoidung_image
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungImage(String nguoidungImage) {
        this.nguoidungImage = nguoidungImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nguoidung.nguoidung_state
     *
     * @return the value of nguoidung.nguoidung_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Boolean getNguoidungState() {
        return nguoidungState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nguoidung.nguoidung_state
     *
     * @param nguoidungState the value for nguoidung.nguoidung_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setNguoidungState(Boolean nguoidungState) {
        this.nguoidungState = nguoidungState;
    }
}