package com.cuduchoa.ThiTracNghiem.model;

import java.util.ArrayList;
import java.util.List;

public class QuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public QuestionExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andQuestionIdIsNull() {
            addCriterion("question_id is null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIsNotNull() {
            addCriterion("question_id is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionIdEqualTo(Long value) {
            addCriterion("question_id =", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotEqualTo(Long value) {
            addCriterion("question_id <>", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThan(Long value) {
            addCriterion("question_id >", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdGreaterThanOrEqualTo(Long value) {
            addCriterion("question_id >=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThan(Long value) {
            addCriterion("question_id <", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdLessThanOrEqualTo(Long value) {
            addCriterion("question_id <=", value, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdIn(List<Long> values) {
            addCriterion("question_id in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotIn(List<Long> values) {
            addCriterion("question_id not in", values, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdBetween(Long value1, Long value2) {
            addCriterion("question_id between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionIdNotBetween(Long value1, Long value2) {
            addCriterion("question_id not between", value1, value2, "questionId");
            return (Criteria) this;
        }

        public Criteria andQuestionContentIsNull() {
            addCriterion("question_content is null");
            return (Criteria) this;
        }

        public Criteria andQuestionContentIsNotNull() {
            addCriterion("question_content is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionContentEqualTo(String value) {
            addCriterion("question_content =", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentNotEqualTo(String value) {
            addCriterion("question_content <>", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentGreaterThan(String value) {
            addCriterion("question_content >", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentGreaterThanOrEqualTo(String value) {
            addCriterion("question_content >=", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentLessThan(String value) {
            addCriterion("question_content <", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentLessThanOrEqualTo(String value) {
            addCriterion("question_content <=", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentLike(String value) {
            addCriterion("question_content like", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentNotLike(String value) {
            addCriterion("question_content not like", value, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentIn(List<String> values) {
            addCriterion("question_content in", values, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentNotIn(List<String> values) {
            addCriterion("question_content not in", values, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentBetween(String value1, String value2) {
            addCriterion("question_content between", value1, value2, "questionContent");
            return (Criteria) this;
        }

        public Criteria andQuestionContentNotBetween(String value1, String value2) {
            addCriterion("question_content not between", value1, value2, "questionContent");
            return (Criteria) this;
        }

        public Criteria andAnswerOneIsNull() {
            addCriterion("answer_one is null");
            return (Criteria) this;
        }

        public Criteria andAnswerOneIsNotNull() {
            addCriterion("answer_one is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerOneEqualTo(String value) {
            addCriterion("answer_one =", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotEqualTo(String value) {
            addCriterion("answer_one <>", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneGreaterThan(String value) {
            addCriterion("answer_one >", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneGreaterThanOrEqualTo(String value) {
            addCriterion("answer_one >=", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneLessThan(String value) {
            addCriterion("answer_one <", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneLessThanOrEqualTo(String value) {
            addCriterion("answer_one <=", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneLike(String value) {
            addCriterion("answer_one like", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotLike(String value) {
            addCriterion("answer_one not like", value, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneIn(List<String> values) {
            addCriterion("answer_one in", values, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotIn(List<String> values) {
            addCriterion("answer_one not in", values, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneBetween(String value1, String value2) {
            addCriterion("answer_one between", value1, value2, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerOneNotBetween(String value1, String value2) {
            addCriterion("answer_one not between", value1, value2, "answerOne");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoIsNull() {
            addCriterion("answer_two is null");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoIsNotNull() {
            addCriterion("answer_two is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoEqualTo(String value) {
            addCriterion("answer_two =", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoNotEqualTo(String value) {
            addCriterion("answer_two <>", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoGreaterThan(String value) {
            addCriterion("answer_two >", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoGreaterThanOrEqualTo(String value) {
            addCriterion("answer_two >=", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoLessThan(String value) {
            addCriterion("answer_two <", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoLessThanOrEqualTo(String value) {
            addCriterion("answer_two <=", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoLike(String value) {
            addCriterion("answer_two like", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoNotLike(String value) {
            addCriterion("answer_two not like", value, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoIn(List<String> values) {
            addCriterion("answer_two in", values, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoNotIn(List<String> values) {
            addCriterion("answer_two not in", values, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoBetween(String value1, String value2) {
            addCriterion("answer_two between", value1, value2, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerTwoNotBetween(String value1, String value2) {
            addCriterion("answer_two not between", value1, value2, "answerTwo");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeIsNull() {
            addCriterion("answer_three is null");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeIsNotNull() {
            addCriterion("answer_three is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeEqualTo(String value) {
            addCriterion("answer_three =", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeNotEqualTo(String value) {
            addCriterion("answer_three <>", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeGreaterThan(String value) {
            addCriterion("answer_three >", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeGreaterThanOrEqualTo(String value) {
            addCriterion("answer_three >=", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeLessThan(String value) {
            addCriterion("answer_three <", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeLessThanOrEqualTo(String value) {
            addCriterion("answer_three <=", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeLike(String value) {
            addCriterion("answer_three like", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeNotLike(String value) {
            addCriterion("answer_three not like", value, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeIn(List<String> values) {
            addCriterion("answer_three in", values, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeNotIn(List<String> values) {
            addCriterion("answer_three not in", values, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeBetween(String value1, String value2) {
            addCriterion("answer_three between", value1, value2, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerThreeNotBetween(String value1, String value2) {
            addCriterion("answer_three not between", value1, value2, "answerThree");
            return (Criteria) this;
        }

        public Criteria andAnswerFourIsNull() {
            addCriterion("answer_four is null");
            return (Criteria) this;
        }

        public Criteria andAnswerFourIsNotNull() {
            addCriterion("answer_four is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerFourEqualTo(String value) {
            addCriterion("answer_four =", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourNotEqualTo(String value) {
            addCriterion("answer_four <>", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourGreaterThan(String value) {
            addCriterion("answer_four >", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourGreaterThanOrEqualTo(String value) {
            addCriterion("answer_four >=", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourLessThan(String value) {
            addCriterion("answer_four <", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourLessThanOrEqualTo(String value) {
            addCriterion("answer_four <=", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourLike(String value) {
            addCriterion("answer_four like", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourNotLike(String value) {
            addCriterion("answer_four not like", value, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourIn(List<String> values) {
            addCriterion("answer_four in", values, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourNotIn(List<String> values) {
            addCriterion("answer_four not in", values, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourBetween(String value1, String value2) {
            addCriterion("answer_four between", value1, value2, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerFourNotBetween(String value1, String value2) {
            addCriterion("answer_four not between", value1, value2, "answerFour");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectIsNull() {
            addCriterion("answer_correct is null");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectIsNotNull() {
            addCriterion("answer_correct is not null");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectEqualTo(String value) {
            addCriterion("answer_correct =", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectNotEqualTo(String value) {
            addCriterion("answer_correct <>", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectGreaterThan(String value) {
            addCriterion("answer_correct >", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectGreaterThanOrEqualTo(String value) {
            addCriterion("answer_correct >=", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectLessThan(String value) {
            addCriterion("answer_correct <", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectLessThanOrEqualTo(String value) {
            addCriterion("answer_correct <=", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectLike(String value) {
            addCriterion("answer_correct like", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectNotLike(String value) {
            addCriterion("answer_correct not like", value, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectIn(List<String> values) {
            addCriterion("answer_correct in", values, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectNotIn(List<String> values) {
            addCriterion("answer_correct not in", values, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectBetween(String value1, String value2) {
            addCriterion("answer_correct between", value1, value2, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andAnswerCorrectNotBetween(String value1, String value2) {
            addCriterion("answer_correct not between", value1, value2, "answerCorrect");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNull() {
            addCriterion("createby is null");
            return (Criteria) this;
        }

        public Criteria andCreatebyIsNotNull() {
            addCriterion("createby is not null");
            return (Criteria) this;
        }

        public Criteria andCreatebyEqualTo(String value) {
            addCriterion("createby =", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotEqualTo(String value) {
            addCriterion("createby <>", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThan(String value) {
            addCriterion("createby >", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyGreaterThanOrEqualTo(String value) {
            addCriterion("createby >=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThan(String value) {
            addCriterion("createby <", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLessThanOrEqualTo(String value) {
            addCriterion("createby <=", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyLike(String value) {
            addCriterion("createby like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotLike(String value) {
            addCriterion("createby not like", value, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyIn(List<String> values) {
            addCriterion("createby in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotIn(List<String> values) {
            addCriterion("createby not in", values, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyBetween(String value1, String value2) {
            addCriterion("createby between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andCreatebyNotBetween(String value1, String value2) {
            addCriterion("createby not between", value1, value2, "createby");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNull() {
            addCriterion("subject_id is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIsNotNull() {
            addCriterion("subject_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectIdEqualTo(Long value) {
            addCriterion("subject_id =", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotEqualTo(Long value) {
            addCriterion("subject_id <>", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThan(Long value) {
            addCriterion("subject_id >", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdGreaterThanOrEqualTo(Long value) {
            addCriterion("subject_id >=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThan(Long value) {
            addCriterion("subject_id <", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdLessThanOrEqualTo(Long value) {
            addCriterion("subject_id <=", value, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdIn(List<Long> values) {
            addCriterion("subject_id in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotIn(List<Long> values) {
            addCriterion("subject_id not in", values, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdBetween(Long value1, Long value2) {
            addCriterion("subject_id between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andSubjectIdNotBetween(Long value1, Long value2) {
            addCriterion("subject_id not between", value1, value2, "subjectId");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeIsNull() {
            addCriterion("question_grade is null");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeIsNotNull() {
            addCriterion("question_grade is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeEqualTo(String value) {
            addCriterion("question_grade =", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeNotEqualTo(String value) {
            addCriterion("question_grade <>", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeGreaterThan(String value) {
            addCriterion("question_grade >", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeGreaterThanOrEqualTo(String value) {
            addCriterion("question_grade >=", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeLessThan(String value) {
            addCriterion("question_grade <", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeLessThanOrEqualTo(String value) {
            addCriterion("question_grade <=", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeLike(String value) {
            addCriterion("question_grade like", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeNotLike(String value) {
            addCriterion("question_grade not like", value, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeIn(List<String> values) {
            addCriterion("question_grade in", values, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeNotIn(List<String> values) {
            addCriterion("question_grade not in", values, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeBetween(String value1, String value2) {
            addCriterion("question_grade between", value1, value2, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionGradeNotBetween(String value1, String value2) {
            addCriterion("question_grade not between", value1, value2, "questionGrade");
            return (Criteria) this;
        }

        public Criteria andQuestionTermIsNull() {
            addCriterion("question_term is null");
            return (Criteria) this;
        }

        public Criteria andQuestionTermIsNotNull() {
            addCriterion("question_term is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionTermEqualTo(String value) {
            addCriterion("question_term =", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermNotEqualTo(String value) {
            addCriterion("question_term <>", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermGreaterThan(String value) {
            addCriterion("question_term >", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermGreaterThanOrEqualTo(String value) {
            addCriterion("question_term >=", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermLessThan(String value) {
            addCriterion("question_term <", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermLessThanOrEqualTo(String value) {
            addCriterion("question_term <=", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermLike(String value) {
            addCriterion("question_term like", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermNotLike(String value) {
            addCriterion("question_term not like", value, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermIn(List<String> values) {
            addCriterion("question_term in", values, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermNotIn(List<String> values) {
            addCriterion("question_term not in", values, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermBetween(String value1, String value2) {
            addCriterion("question_term between", value1, value2, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionTermNotBetween(String value1, String value2) {
            addCriterion("question_term not between", value1, value2, "questionTerm");
            return (Criteria) this;
        }

        public Criteria andQuestionStateIsNull() {
            addCriterion("question_state is null");
            return (Criteria) this;
        }

        public Criteria andQuestionStateIsNotNull() {
            addCriterion("question_state is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionStateEqualTo(Boolean value) {
            addCriterion("question_state =", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateNotEqualTo(Boolean value) {
            addCriterion("question_state <>", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateGreaterThan(Boolean value) {
            addCriterion("question_state >", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("question_state >=", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateLessThan(Boolean value) {
            addCriterion("question_state <", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateLessThanOrEqualTo(Boolean value) {
            addCriterion("question_state <=", value, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateIn(List<Boolean> values) {
            addCriterion("question_state in", values, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateNotIn(List<Boolean> values) {
            addCriterion("question_state not in", values, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateBetween(Boolean value1, Boolean value2) {
            addCriterion("question_state between", value1, value2, "questionState");
            return (Criteria) this;
        }

        public Criteria andQuestionStateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("question_state not between", value1, value2, "questionState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated do_not_delete_during_merge Sat May 28 11:33:34 ICT 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table question
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}