package com.cuduchoa.ThiTracNghiem.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_content
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String questionContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_one
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String answerOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_two
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String answerTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_three
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String answerThree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_four
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String answerFour;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer_correct
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String answerCorrect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.createby
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_grade
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String questionGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_term
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String questionTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Boolean questionState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_id
     *
     * @return the value of question.question_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_id
     *
     * @param questionId the value for question.question_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_content
     *
     * @return the value of question.question_content
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getQuestionContent() {
        return questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_content
     *
     * @param questionContent the value for question.question_content
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setQuestionContent(String questionContent) {
        this.questionContent = questionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_one
     *
     * @return the value of question.answer_one
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getAnswerOne() {
        return answerOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_one
     *
     * @param answerOne the value for question.answer_one
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setAnswerOne(String answerOne) {
        this.answerOne = answerOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_two
     *
     * @return the value of question.answer_two
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getAnswerTwo() {
        return answerTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_two
     *
     * @param answerTwo the value for question.answer_two
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setAnswerTwo(String answerTwo) {
        this.answerTwo = answerTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_three
     *
     * @return the value of question.answer_three
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getAnswerThree() {
        return answerThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_three
     *
     * @param answerThree the value for question.answer_three
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setAnswerThree(String answerThree) {
        this.answerThree = answerThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_four
     *
     * @return the value of question.answer_four
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getAnswerFour() {
        return answerFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_four
     *
     * @param answerFour the value for question.answer_four
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setAnswerFour(String answerFour) {
        this.answerFour = answerFour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer_correct
     *
     * @return the value of question.answer_correct
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getAnswerCorrect() {
        return answerCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer_correct
     *
     * @param answerCorrect the value for question.answer_correct
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setAnswerCorrect(String answerCorrect) {
        this.answerCorrect = answerCorrect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.createby
     *
     * @return the value of question.createby
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.createby
     *
     * @param createby the value for question.createby
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setCreateby(String createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.subject_id
     *
     * @return the value of question.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.subject_id
     *
     * @param subjectId the value for question.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_grade
     *
     * @return the value of question.question_grade
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getQuestionGrade() {
        return questionGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_grade
     *
     * @param questionGrade the value for question.question_grade
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setQuestionGrade(String questionGrade) {
        this.questionGrade = questionGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_term
     *
     * @return the value of question.question_term
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getQuestionTerm() {
        return questionTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_term
     *
     * @param questionTerm the value for question.question_term
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setQuestionTerm(String questionTerm) {
        this.questionTerm = questionTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_state
     *
     * @return the value of question.question_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Boolean getQuestionState() {
        return questionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_state
     *
     * @param questionState the value for question.question_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setQuestionState(Boolean questionState) {
        this.questionState = questionState;
    }
}