package com.cuduchoa.ThiTracNghiem.model;

public class Subject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.subject_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String subjectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subjects.subject_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Boolean subjectState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.subject_id
     *
     * @return the value of subjects.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.subject_id
     *
     * @param subjectId the value for subjects.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.subject_name
     *
     * @return the value of subjects.subject_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getSubjectName() {
        return subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.subject_name
     *
     * @param subjectName the value for subjects.subject_name
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subjects.subject_state
     *
     * @return the value of subjects.subject_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Boolean getSubjectState() {
        return subjectState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subjects.subject_state
     *
     * @param subjectState the value for subjects.subject_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setSubjectState(Boolean subjectState) {
        this.subjectState = subjectState;
    }
}