package com.cuduchoa.ThiTracNghiem.model;

import java.util.Date;

public class Test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_term
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String testTerm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_date
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Date testDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_time_start
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Date testTimeStart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_time_limit
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Integer testTimeLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_quantity
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Integer testQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Boolean testState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_grade
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private String testGrade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_id
     *
     * @return the value of test.test_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_id
     *
     * @param testId the value for test.test_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.subject_id
     *
     * @return the value of test.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.subject_id
     *
     * @param subjectId the value for test.subject_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_term
     *
     * @return the value of test.test_term
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getTestTerm() {
        return testTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_term
     *
     * @param testTerm the value for test.test_term
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestTerm(String testTerm) {
        this.testTerm = testTerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_date
     *
     * @return the value of test.test_date
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Date getTestDate() {
        return testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_date
     *
     * @param testDate the value for test.test_date
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestDate(Date testDate) {
        this.testDate = testDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_time_start
     *
     * @return the value of test.test_time_start
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Date getTestTimeStart() {
        return testTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_time_start
     *
     * @param testTimeStart the value for test.test_time_start
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestTimeStart(Date testTimeStart) {
        this.testTimeStart = testTimeStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_time_limit
     *
     * @return the value of test.test_time_limit
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Integer getTestTimeLimit() {
        return testTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_time_limit
     *
     * @param testTimeLimit the value for test.test_time_limit
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestTimeLimit(Integer testTimeLimit) {
        this.testTimeLimit = testTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_quantity
     *
     * @return the value of test.test_quantity
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Integer getTestQuantity() {
        return testQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_quantity
     *
     * @param testQuantity the value for test.test_quantity
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestQuantity(Integer testQuantity) {
        this.testQuantity = testQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_state
     *
     * @return the value of test.test_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Boolean getTestState() {
        return testState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_state
     *
     * @param testState the value for test.test_state
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestState(Boolean testState) {
        this.testState = testState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_grade
     *
     * @return the value of test.test_grade
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public String getTestGrade() {
        return testGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_grade
     *
     * @param testGrade the value for test.test_grade
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestGrade(String testGrade) {
        this.testGrade = testGrade;
    }
}