package com.cuduchoa.ThiTracNghiem.model;

public class Test_detailKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail.test_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail.question_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail.test_id
     *
     * @return the value of test_detail.test_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail.test_id
     *
     * @param testId the value for test_detail.test_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail.question_id
     *
     * @return the value of test_detail.question_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail.question_id
     *
     * @param questionId the value for test_detail.question_id
     *
     * @mbg.generated Sat May 28 11:33:34 ICT 2022
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}